export const industries = [
  { id: 'distribution-logistics', name: 'Distribution & Logistics' },
  { id: 'retail-commerce', name: 'Retail & Commerce' },
  { id: 'ecommerce-digital-commerce', name: 'E-commerce & Digital Commerce' },
  { id: 'hospitality-fnb', name: 'Hospitality & Food & Beverage' },
  { id: 'travel-tourism', name: 'Travel & Tourism' },
  { id: 'healthcare-medical', name: 'Healthcare & Medical' },
  { id: 'education-training', name: 'Education & Training' },
  { id: 'professional-services', name: 'Professional Services' },
  { id: 'construction-real-estate', name: 'Construction & Real Estate' },
  { id: 'manufacturing-production', name: 'Manufacturing & Production' },
  { id: 'agriculture-agribusiness', name: 'Agriculture & Agribusiness' },
  { id: 'automotive-mobility', name: 'Automotive & Mobility' },
  { id: 'finance-membership', name: 'Finance & Membership Organizations' },
  { id: 'public-sector-ngos', name: 'Public Sector & NGOs' },
  { id: 'energy-utilities', name: 'Energy & Utilities' },
  { id: 'media-creative', name: 'Media & Creative Industries' },
  { id: 'home-personal-services', name: 'Home & Personal Services' },
  { id: 'technology-saas', name: 'Technology & SaaS' },
  { id: 'mining-extractives', name: 'Mining & Extractives' },
  { id: 'multi-industry-groups', name: 'Multi-Industry Groups' },
]

export const plugCatalog = {
  operations: {
    title: 'Business Operations',
    shortTitle: 'Operations',
    subtitle: 'Execution workflows for POS, stock, procurement, customers, teams, and operational control.',
    modules: [
      {
        id: 'sales-revenue',
        name: 'Sales & Revenue Operations',
        submodules: [
          'POS transactions',
          'Invoice generation',
          'Quotation creation',
          'Order processing',
          'Sales returns & refunds',
          'Discount & promotion management',
          'Multi-channel sales',
          'Credit sales & receivables',
        ],
      },
      {
        id: 'inventory-stock',
        name: 'Inventory & Stock Operations',
        submodules: [
          'Product catalog management',
          'SKU & barcode management',
          'Stock-in / stock-out recording',
          'Batch & serial tracking',
          'Reorder level alerts',
          'Inter-branch stock transfer',
          'Damaged/expired stock logging',
          'Physical stock reconciliation',
        ],
      },
      {
        id: 'procurement-suppliers',
        name: 'Procurement & Supplier Operations',
        submodules: [
          'Supplier database',
          'Purchase orders',
          'Goods receipt',
          'Supplier invoice capture',
          'Purchase returns',
          'Supplier performance tracking',
          'Supply contract management',
          'Price comparison tracking',
        ],
      },
      {
        id: 'customer-operations',
        name: 'Customer Operations',
        submodules: [
          'Customer database',
          'Loyalty programs',
          'Customer segmentation',
          'Credit tracking',
          'Complaint logging',
          'After-sales service',
          'Warranty tracking',
          'CRM-lite interactions',
        ],
      },
      {
        id: 'workforce-task',
        name: 'Workforce & Task Operations',
        submodules: [
          'Attendance tracking',
          'Shift scheduling',
          'Role-based access',
          'Task assignment',
          'Performance logs',
          'Commission & incentives',
          'Operational productivity',
        ],
      },
      {
        id: 'financial-transactions',
        name: 'Financial Transaction Operations',
        submodules: [
          'Daily cash reconciliation',
          'Bank reconciliation',
          'Expense logging',
          'Petty cash tracking',
          'Operational budgeting',
          'Multi-currency handling',
          'Tax tagging',
        ],
      },
      {
        id: 'reporting-analytics',
        name: 'Reporting & Operational Analytics',
        submodules: [
          'Daily sales reports',
          'Inventory movement reports',
          'Expense summaries',
          'Cash flow snapshots',
          'Branch performance comparison',
          'Product performance reports',
          'Operational efficiency metrics',
        ],
      },
      {
        id: 'compliance-control',
        name: 'Compliance & Control Operations',
        submodules: [
          'Audit trail logging',
          'Role-based permissions',
          'Fraud detection flags',
          'Approval workflows',
          'Data backup & security logging',
        ],
      },
    ],
  },
  management: {
    title: 'Management',
    shortTitle: 'Management',
    subtitle: 'Strategic planning, KPI oversight, risk posture, growth, and executive intelligence.',
    modules: [
      {
        id: 'strategic-planning',
        name: 'Strategic Planning & Direction',
        submodules: [
          'Vision and mission alignment',
          'Strategic goal setting',
          'OKR management',
          'Annual and quarterly planning',
          'Expansion planning',
          'Competitive benchmarking',
          'Scenario modeling',
        ],
      },
      {
        id: 'performance-management',
        name: 'Performance Management',
        submodules: [
          'KPI definition and tracking',
          'Revenue growth tracking',
          'Profit margin analysis',
          'Cost efficiency analysis',
          'Branch performance comparison',
          'Employee performance dashboards',
          'Benchmark comparison',
        ],
      },
      {
        id: 'financial-oversight',
        name: 'Financial Oversight',
        submodules: [
          'Budget approval and tracking',
          'Revenue and cost forecasting',
          'Cash flow forecasting',
          'Break-even analysis',
          'Capital allocation',
          'ROI tracking',
          'Cost center analysis',
        ],
      },
      {
        id: 'sales-revenue-management',
        name: 'Sales & Revenue Management',
        submodules: [
          'Sales target setting',
          'Sales pipeline oversight',
          'Channel performance analysis',
          'Customer lifetime value',
          'Pricing strategy',
          'Discount policy governance',
          'Promotion effectiveness',
        ],
      },
      {
        id: 'operations-oversight',
        name: 'Operations Oversight',
        submodules: [
          'Operational efficiency monitoring',
          'Inventory turnover analysis',
          'Supply chain performance metrics',
          'Capacity utilization tracking',
          'Vendor performance evaluation',
          'Quality performance tracking',
        ],
      },
      {
        id: 'workforce-org-management',
        name: 'Workforce & Organizational Management',
        submodules: [
          'Org structure management',
          'Workforce planning',
          'Talent evaluation',
          'Compensation oversight',
          'Training effectiveness',
          'Turnover analysis',
          'Leadership performance',
        ],
      },
      {
        id: 'risk-compliance-management',
        name: 'Risk & Compliance Management',
        submodules: [
          'Regulatory risk monitoring',
          'Fraud risk monitoring',
          'Incident oversight',
          'Control effectiveness review',
          'Audit performance monitoring',
          'Business continuity planning',
        ],
      },
      {
        id: 'customer-market-management',
        name: 'Customer & Market Management',
        submodules: [
          'Customer acquisition metrics',
          'Retention tracking',
          'Satisfaction scoring',
          'Complaint trend analysis',
          'Demand forecasting',
          'Market expansion analysis',
        ],
      },
      {
        id: 'innovation-growth-management',
        name: 'Innovation & Growth Management',
        submodules: [
          'Product development tracking',
          'Innovation pipeline',
          'Technology adoption',
          'Digital transformation',
          'Partnership evaluation',
          'New branch rollout',
        ],
      },
      {
        id: 'executive-intelligence',
        name: 'Reporting & Executive Intelligence',
        submodules: [
          'Executive dashboards',
          'Real-time alerts',
          'Board reporting',
          'Shareholder reporting',
          'Data visualization',
          'Automated executive summaries',
        ],
      },
    ],
  },
  administration: {
    title: 'Administration',
    shortTitle: 'Administration',
    subtitle: 'Governance backbone for finance, HR, legal compliance, contracts, records, and risk.',
    modules: [
      {
        id: 'financial-administration',
        name: 'Financial Administration',
        submodules: [
          'General ledger',
          'Accounts payable',
          'Accounts receivable',
          'Payroll processing',
          'Tax calculation and reporting',
          'Bank reconciliation',
          'Fixed asset register',
          'Financial statement generation',
        ],
      },
      {
        id: 'hr-administration',
        name: 'Human Resource Administration',
        submodules: [
          'Employee records',
          'Contract storage',
          'Benefits administration',
          'Leave management',
          'Onboarding documentation',
          'Exit processing',
          'Role and access authorization',
        ],
      },
      {
        id: 'legal-compliance-administration',
        name: 'Legal & Compliance Administration',
        submodules: [
          'Business registration docs',
          'Licensing management',
          'Permit tracking',
          'Regulatory filing reminders',
          'Policy documentation',
          'Contract renewal alerts',
          'Data protection logs',
        ],
      },
      {
        id: 'governance-internal-control',
        name: 'Governance & Internal Control',
        submodules: [
          'Approval hierarchy',
          'Internal audit scheduling',
          'Fraud investigation logs',
          'Board resolutions',
          'Governance policies',
          'Access control auditing',
          'Risk register maintenance',
        ],
      },
      {
        id: 'procurement-contract-administration',
        name: 'Procurement & Contract Administration',
        submodules: [
          'Vendor contract storage',
          'Procurement workflows',
          'Tender documentation',
          'SLA monitoring',
          'Renewal alerts',
          'Vendor compliance verification',
        ],
      },
      {
        id: 'asset-infrastructure-administration',
        name: 'Asset & Infrastructure Administration',
        submodules: [
          'Asset tagging',
          'Equipment registration',
          'Maintenance scheduling',
          'Lease agreements',
          'Facility documentation',
          'Disposal documentation',
        ],
      },
      {
        id: 'data-records-administration',
        name: 'Data & Records Administration',
        submodules: [
          'Document management',
          'Secure data storage',
          'Access logging',
          'Data retention policies',
          'Backup and recovery logs',
          'Digital signature tracking',
        ],
      },
      {
        id: 'risk-insurance-administration',
        name: 'Risk & Insurance Administration',
        submodules: [
          'Risk documentation',
          'Incident reporting',
          'Insurance policy tracking',
          'Claims documentation',
          'Business continuity docs',
          'Emergency protocol storage',
        ],
      },
    ],
  },
}

export function getPlugDefinition(plugKey) {
  return plugCatalog[plugKey]
}
